--DROP DATABASE SampleEcommerceDb;
CREATE DATABASE SampleEcommerceDb;
GO
USE SampleEcommerceDb;
GO
CREATE TABLE Users (
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name NVARCHAR(100) NOT NULL,
	Email NVARCHAR(100) NOT NULL UNIQUE,
	Password NVARCHAR(MAX) NOT NULL,
	Seller BIT NOT NULL DEFAULT 0,
	Iva NVARCHAR(11),
	TradingName NVARCHAR(100),
	EmailConfirmed BIT NOT NULL DEFAULT 0,
	EmailConfirmationToken NVARCHAR(MAX) NULL,
	PasswordResetToken NVARCHAR(MAX) NULL,
	PasswordResetTokenExpiry DATETIME NULL,
);
GO
CREATE TABLE Addresses(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Country NVARCHAR(50) NOT NULL,
	Receiver NVARCHAR(100) NOT NULL,
	Phone VARCHAR(50),
	StreetAdress NVARCHAR(250) NOT NULL,
	ComplementAddress NVARCHAR(250) NOT NULL,
	ZipCode VARCHAR(25) NOT NULL,
	City NVARCHAR(100) NOT NULL,
	Province NVARCHAR(100) NOT NULL,
	IsActive BIT NOT NULL DEFAULT 1,
);
GO
CREATE TABLE UserAddresses (
    UserId UNIQUEIDENTIFIER NOT NULL,
    AddressId INT NOT NULL,
	IsPreferred BIT NOT NULL DEFAULT 0,
    PRIMARY KEY (UserId, AddressId),
    FOREIGN KEY (UserId) REFERENCES Users(Id),
    FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
);
GO
CREATE UNIQUE INDEX UX_UserAddress_OnePreferredPerUser
ON UserAddresses(UserId)
WHERE IsPreferred = 1;
GO
CREATE TABLE Products(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	Name NVARCHAR(250) NOT NULL,
	Brand NVARCHAR(50) NOT NULL,
	Description NVARCHAR(MAX) NOT NULL,
	ImageUrl NVARCHAR(500) NULL,
	IsActive BIT DEFAULT 1,
	TotalReviews INT NOT NULL DEFAULT 0,
	MediaReviews FLOAT NOT NULL DEFAULT 0,
	SellerId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (SellerId) REFERENCES Users(Id)
);
GO
CREATE TABLE StockKeepingUnits(
	Id UNIQUEIDENTIFIER PRIMARY KEY DEFAULT NEWID(),
	ProductId UNIQUEIDENTIFIER NOT NULL,
	Price DECIMAL(18,2) NOT NULL,
	Stock INT NOT NULL,
	Features NVARCHAR(MAX) NOT NULL,
	FOREIGN KEY (ProductId) REFERENCES Products(Id)
);
GO
CREATE TABLE Reviews(
	Id INT PRIMARY KEY IDENTITY(1,1),
	Rate INT NOT NULL CHECK (Rate >= 1 AND Rate <= 5),
	Comment NVARCHAR(100),
	ReviewDate DATETIME DEFAULT GETDATE(),
	
	ProductId UNIQUEIDENTIFIER NOT NULL,
	UserId UNIQUEIDENTIFIER NOT NULL,
	FOREIGN KEY (ProductId) REFERENCES Products(Id),
	FOREIGN KEY (UserId) REFERENCES Users(Id),

	CONSTRAINT UC_User_Product UNIQUE (UserId, ProductId)
);
GO
CREATE TABLE Orders(
	Id INT PRIMARY KEY IDENTITY(1,1),
	CreatedAt DATETIME DEFAULT GETDATE(),
	TotalPrice DECIMAL(18,2) NOT NULL,
	
	UserId UNIQUEIDENTIFIER NOT NULL,
	AddressId INT NOT NULL,
	FOREIGN KEY (UserId) REFERENCES Users(Id),
	FOREIGN KEY (AddressId) REFERENCES Addresses(Id)
);
GO
CREATE TABLE OrderItems(
	OrderId INT NOT NULL,
    SkuId UNIQUEIDENTIFIER NOT NULL,
    Quantity INT NOT NULL,
    MomentPrice DECIMAL(18,2),
    PRIMARY KEY (OrderId, SkuId),
    FOREIGN KEY (OrderId) REFERENCES Orders(Id),
    FOREIGN KEY (SkuId) REFERENCES StockKeepingUnits(Id)
);
GO
